version: '3.9'

services:
  db:
    image: postgres:16.2
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pomodoro

  cache:
    image: redis:7.2.4-alpine
    ports:
      - "6379:6379"

  # rabbitmq:
  #   image: "rabbitmq:management"
  #   hostname: rabbitmq_test
  #   restart: always
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   volumes:
  #     - ./rabbitmq_data:/var/lib/rabbitmq
  #   environment:
  #     - RABBITMQ_DEFAULT_USER=admin
  #     - RABBITMQ_DEFAULT_PASS=password
  #     - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766